### ISSUE TITLE
Generate a few Multiple Sequence Alignment Files with flu HA genes

### ISSUE THREAD

**Issue by Deena-B** [deepcelllineage/fluHA#1]
# Align flu HA genes & visualize the differences between sequences

## Aims

1. Align 10, 100, and 1000 flu HA gene sequences
2. View alignment 
3. Minimize the number and length of gaps between nucleotides
4. Report which alignment packages were tested and which package and settings were best for aim 3

## Background

Choosing an aligner is an important part of bioinformatics. Different types of files require different aligners. For example [bwa](http://bio-bwa.sourceforge.net/) and [bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) are commonly used to align short reads to a human reference genome. 

Aligning flu genes requires a very different type of aligner - an aligner for medium-length gene segments that are all (at least close to) the same length.

## Purpose 

Aligning medium-length reads is a step that precedes creating a consensus sequence and a phylogenetic tree, which help us understand variability in a genome. 

## Methods

We need to generate multiple sequence alignment (msa) files in the Phylip format. SciKit-Bio gives a straight forward and simple [explanation of Phylip](http://scikit-bio.org/docs/0.5.5/generated/skbio.io.format.phylip.html).

### Aligners

In the past I have used a GUI and [MUSCLE or MAFT algorithms](https://www.ebi.ac.uk/Tools/msa/) to align flu genes with very similar sequences and it worked very well, except I couldn't extract the valuable variability information from the GUI in an efficient manner.

For suggestions on which aligners to use, check out the following links:

[Biostars forum](https://www.biostars.org/t/Forum/)

Wikipedia has a list of alignment visualization software [here](https://en.wikipedia.org/wiki/List_of_alignment_visualization_software)

BioPython - see the [AlignIO module](https://biopython.org/wiki/AlignIO)

- [Docs](https://biopython.org/) 
- [Github](https://github.com/biopython/biopython/) 

SciKit-Bio - see [Align](http://scikit-bio.org/docs/0.4.2/alignment.html?highlight=align#module-skbio.alignment), [Phylip format](http://scikit-bio.org/docs/0.4.2/generated/skbio.io.format.phylip.html?highlight=multiple%20sequence%20alignment), and [Consensus](http://scikit-bio.org/docs/0.4.2/generated/skbio.alignment.TabularMSA.consensus.html)

- [Docs](http://scikit-bio.org/)
- [Github](https://github.com/biocore/scikit-bio) 

### Viewers

From the SciKit-Bio Cookbook, see [Alignment Viewing](https://nbviewer.jupyter.org/github/biocore/scikit-bio-cookbook/blob/master/Alignment%20viewing%20and%20filtering.ipynb) 

### Data

For data, download flu HA .fasta files by following instructions here: [dwnld-flu-fa.md](https://github.com/deepcelllineage/overview/wiki/dwnld-flu-fa)

- instead of picking only human virus isolates, also include some swine, horse, dog, and avian isolates to get more variety 
- to further increase variety and the gaps that appear in your alignment, download sequences for multiple HA subtypes, i.e. H1, H2, H3, H5, H7, & H9

Related to [mitolin issue 7](https://github.com/deepcelllineage/mitolin/issues/7)

## Document your work

Please fork & clone this repo. Check out a branch for your work, then push and make a PR for us to merge your notes & code to this repo. For an outline of how DCL repos are organized, see [dir-struct.md](https://github.com/deepcelllineage/overview/wiki/dir-struct) in the overview wiki. Remember to .gitignore large data files, e.g. `*.fasta` and use `.keep` files to make git track directories that only have ignored files in them. 

## Questions? 

Please put questions related to this issue in this issue thread. If you want a quick response, post a link to your comment in this thread to Slack #deepcelllineage or DM @Deena. To join Slack enter your email address [here](http://bit.ly/JoinSlackFastaiSFbay). For questions NOT specifically related to this issue, get in touch through any of the communication methods listed in [DCL's overview README](https://github.com/deepcelllineage/overview/blob/master/README.md).

**Comment by bl2e** [comment]
The aims of this issue were implemented.  Based on the results and recommendations from Deena, it makes sense to close issue #1, and create another that aligns H3N2 samples.  Aligners and viewers will be documented in the wiki.  Link to related issue will follow.

**Comment by bl2e** [comment]
See issue #4
